export interface IMarketDcumentFromBMF_PTBR {
  id: string;
  descricaoFundo: string;
  categoriaDocumento: string;
  tipoDocumento: string;
  especieDocumento: string;
  dataReferencia: string;
  dataEntrega: string;
  status: string;
  descricaoStatus: string;
  analisado: 'S' | 'N';
  situacaoDocumento: string;
  assuntos: string[] | null;
  altaPrioridade: boolean;
  formatoDataReferencia: string;
  versao: number;
  modalidade: string;
  descricaoModalidade: string;
  nomePregao: string;
  informacoesAdicionais: string;
  arquivoEstruturado: string;
  formatoEstruturaDocumento: string | null;
  nomeAdministrador: string | null;
  cnpjAdministrador: string | null;
  cnpjFundo: string | null;
  idFundo: number | null;
  idTemplate: number;
  idSelectNotificacaoConvenio: number | null;
  idSelectItemConvenio: number;
  indicadorFundoAtivoB3: boolean;
  idEntidadeGerenciadora: number | null;
  ofertaPublica: string | null;
  numeroEmissao: number | null;
  tipoPedido: string | null;
  dda: string | null;
  codSegNegociacao: string | null;
  fundoOuClasse: string | null;
  nomePrimeiraVisualizacao: string | null;
}